apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrierkavpeer1ibft
  namespace: carrierkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrierkavpeer1ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: besu-privateTx
    path: platforms/hyperledger-besu/charts/node_besu
  values:
    metadata:
      namespace: carrierkav-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://b636842cb17d1330b2c823c5c59f148c3354a1969f6f11101c6647a34e7040b8dd3cd8ce817c0502743a86bc66e76e65f774c2541796e82495b901d6092e775d@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      - "enode://fe30499336f8eaaa75a1fbc443d62c0f5472253e3190aa255bb86a3d707ed99859ebd23e2e5776dcc4fc5ba73370aded18839386a5b7c391fd2bda02441acd49@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      - "enode://7d5625e24f19d54f07479589bc88f18f8eb38d8e50d5a1356e569142f6347a94627fca225f25ce2257953a3fee4485cfd9abb673899fd236a03c0c4998dc4315@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      - "enode://7a6f651758155dfee9b36cbe83fda4044beeb86fa9882603b68f21cb017036276b35106f5d624d4eb914187c46ace4255f93b0fceeeffa2fbab225d4426449b6@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      - "enode://c45257f7fc7286170fba95542a828a864c84b8c565b50938a66d6aed9c7a5e9019971a36026c5bb87c0e24aa371141887042afd4bb43f63b4c5567b3ac85b136@peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      - "enode://762ec5a51217d0a7ba35caaf417810b98833cfdd1b1eba7fdf725d628bbe4c627387f56b1f2d55ae5369c77534f33a0e0a3d083647c5b2936f9f1ec59459891a@peer2.bes.dev2.aws.blockchaincloudpoc-develop.com:15062"
      - "enode://e714c3b5bf4773a70a2c43d44b95a1dc2e4a5569dd9879e476e78ebe8c17a614b77c0a32b2063ce89b7deb1ecd923f2132c8f5efc173fff4bf6b9624d67e795b@peer3.bes.dev2.aws.blockchaincloudpoc-develop.com:15065"
      - "enode://4e8fe209aa0107be02ae67718136c33b3038a0ed4b2e48e3b51e74329f4b691f74d51af61019b6c635faca2312cd4fa18e8014756957cf78e74e1e6d0bcb2b88@peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:15068"
   

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
 
    proxy:
      provider: ambassador
      external_url: carrierkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15049
      rpc: 15050

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0     

    node:
      name: peer1
      consensus: ibft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      
      url: "https://peer1-tessera.carrierkav-bes:8888"
      
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/carrierkav-bes/crypto/peer1
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarrierkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGMxYTMzNzc3MWNlZGUyMzlhMzM1ZmMwOWIyMzU3NGU2YmQxYzk0MzM5NGE0NWI0YmM3YzZiMzgyOWVkNmY1OTdjNGYxNmI0YzFlYjAxMTE1NmU5NGQ2YTA0YTJiZTA2NDg0ZmMzN2M1YTBkYWJmNTZkNWIzMTQ5ODQ0YzM5NDdmNzVkOTFhYzkxZGFkZjBlZTZkZmViNTMzZTdlZjk3Mjc1ZmM4YWU4MDg0MDAwMDAwMDBjMCIKfQ==
