apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrierkavpeer2ibft
  namespace: carrierkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrierkavpeer2ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: besu-privateTx
    path: platforms/hyperledger-besu/charts/node_besu
  values:
    metadata:
      namespace: carrierkav-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://2e4feddf67808cf1140086bea3caeaf082a9082b5f2e3cdf766f44c6a0fcec93be15ce8f72a825ec4f7e0a88333330f671fe8f04b8abe71cf42bc40ebc6210e1@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      - "enode://73b85301f0a61132f4cf4aee2c82070eaf48c5b6873a73c8ca1351c7f2f13cce20f6a1d5d1966d1761015d4ebccf431ddb0d11eb2aaf64b5e4fed10938f165fa@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      - "enode://76b76c85e3aead012f5e473a4d3938e2cb9adbbcd515fb22f4e14df2a87c8596355691628d7be0e69ebe5a0523befe03865a177b1e6635843e24fab428a33282@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      - "enode://215643c25bf7e07ced7296cfb3ce5320688536f006eb4af48d416c5e7ef87174cb65d89aba341468b9b33e73828e80071a95ff6c52ca4f059dd3e51e075813e9@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      - "enode://7deaca725b41a51fe3ab72dddf18bc7eb5ee00e36ea420779ac32d518032897ab6a3a09ffb1f4305827284d82e732c8dcd4529389aad458b7bab42bbb118d3f9@peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      - "enode://0bcf17be5854a811b00c81bd5936f6de25783a79667687828fbf307779e502235c2cc62bde5ef7b4be2ea918ca894da26b754835f56ca3dbb99e8e53de63fc7e@peer2.bes.dev2.aws.blockchaincloudpoc-develop.com:15062"
      - "enode://6ebbd3e67de4b71c02a4db76b8c14dfc5031a33617b9e5e22686892ca2a8bb60a03ed455d1f0d233cac1135091cdff98c11773354154e3133ee188b1e81cdd96@peer3.bes.dev2.aws.blockchaincloudpoc-develop.com:15065"
      - "enode://4b9123673563c954e637fa741faa55ce4de8965e16ac1dece884b5524acb511b04ca2c82783d89a15d4db70d4c568bbfdb7fd7682d70dadc1d1fcdf6bb9c8ebc@peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:15068"
   

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
 
    proxy:
      provider: ambassador
      external_url: carrierkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15062
      rpc: 15063

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0     

    node:
      name: peer2
      consensus: ibft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    tm:
      type: tessera
      tls: True
      
      url: "https://peer2-tessera.carrierkav-bes:8888"
      
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/carrierkav-bes/crypto/peer2
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarrierkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGIxYmNlMzA1MTAwODM4NDIwOGZkNjk4ODhiNTBiZWMwMzE3YjdlZDI5NGY1MTRiNzQyYWMyNjg4NTIwNWUyZmFhNGQzOWVlMDliZDc3MzI5MjU5NDFkYjg4M2IyYzVhMDRiNDJkMjMwNTI1MGExNmVkZTM4OGZkMDYzZjU5NDBkNWFkMzRkYmExNjA3MGM1ODZiMDUyNTg2Yzg3MzliNTQ2MTFmNDQ4MDg0MDAwMDAwMDBjMCIKfQ==
