apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrierkavpeer3ibft
  namespace: carrierkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrierkavpeer3ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: besu-privateTx
    path: platforms/hyperledger-besu/charts/node_orion 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://6c0f4f916ef8e28fd689c4ef7c60d3ae1ad61c39fa0229334e6dafc9e21dd2b9a1a0f32a60d09038165291cbd15b90cf7d89de6a094db205bfefeb8896617112@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      - "enode://932fe597a700acc16f01f394b48fd81acb0f4aebe1fc6fb95ec04ddafe87dfc2f76a05f45f3099c885e4195a40e3a1cda3de079131dcdb93e2a3f5028fb9f586@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      - "enode://e0ee1ce3ab064d626bffd718e7a3c8272134308c377440ae0d700b5f887952d17b14141019c71f64262457ae0a042ba8cfd885600f9516f0ca27be054cb34eef@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      - "enode://08d432905344b33e4a647c1b2e97a4c7ae64421c366d65fecd4610ebd835b216f73bc505df9b4f9ea293f94a2c322f264ac25fecc6f9d3fe61561e7609b53a9e@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      - "enode://705c70e89f41e6719055eb308fe6d4ca37fcf8750fdd26c4de78637aff760f4bfc55d285769da2a87663fb98feb36d3ede4c969cf9d329eb3ac90f785629b646@peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      - "enode://ac50fea146a2b91c3b807603395286590429c38258b15352102f6ae01c88b39b5d6af1961f67b82dc80a73538b34297d3d386292b726e658427c549797523cc4@peer2.bes.dev2.aws.blockchaincloudpoc-develop.com:15062"
      - "enode://c67942ab049309fd2b4e281f36d17bdc342f698443e18ddf88e86c91dcaca4dc2d28d4bd523bb46da3ab883bdcb964f9c7b8d41b3ff2c930bd83849997871f88@peer3.bes.dev2.aws.blockchaincloudpoc-develop.com:15065"
      - "enode://15adeec6ab6694e23fc6695a4995946d15f2eefcf3c5b5e85a715a7235757205813643bb5598886d2ee69f60a42a08a7c316f1ff02eacad8be6aaa540b54b2cb@peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:15068"

    metadata:
      namespace: carrierkav-bes
      labels:

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: carrierkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15065
      rpc: 15066
      tmport: 15067

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0
      orion: pegasyseng/orion:21.1.1

    node:
      name: peer3
      consensus: ibft
      subject: O=Carrier,OU=Carrier,L=51.50/-0.13/London,C=GB
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    orion:
      name: orion
      tls: True
      confdir: /etc/config
      url: "https://carrierkav.bes.dev2.aws.blockchaincloudpoc-develop.com"
      nodelist: "\"https://peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15061\",\"https://peer2.bes.dev2.aws.blockchaincloudpoc-develop.com:15064\",\"https://peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:15070\""
      trust: ca-or-tofu
      ports:
        nodeport: 8888
        clientport: 8080

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/carrierkav-bes/crypto/peer3
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarrierkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGY5NTZlZTdmYWU4YzRiMGEyOTNlZjY3MWU4ZmMxNGM1Yzg1YTNlMzU5NDAwMGQzYzJjZjUwZDdiNjUzYTQ5NWI5NDg4YmE2ODMxZjIwMzQ2ZGI5NDFmNjkzOTQ0ZDIzN2U2ODcxNTk1ZDZmMTJiNDg1OTUzZWZhZjhhYTc5NGVkYTI5ZDA4ZmFmZGYwMzY1OTViOWE5ZTc3ODgzNGNjYTExMTBlNWY4MDg0MDAwMDAwMDBjMCIKfQ==
