apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: peer4tessera
  namespace: carrierkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: peer4tessera
  helmVersion: v3
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: besu-privateTx
    path: platforms/hyperledger-besu/charts/node_tessera  
  values:
    replicaCount: 1
    metadata:
      namespace: carrierkav-bes
      labels:
    images:      
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.1.1
      busybox: busybox
      mysql: mysql/mysql-server:5.7
      imagePullSecret: regcred
    tessera:
      name: peer4-tessera
      dbname: demodb      
      dburl: "jdbc:mysql://peer4-tessera:3306/demodb"
      dbusername: demouser
      tls: "STRICT"
 
      url: "https://peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:443"
      
      clienturl: "https://peer4-tessera:8888"
      othernodes:
        - url: http://peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:443
        - url: http://peer2.bes.dev2.aws.blockchaincloudpoc-develop.com:443
        - url: http://peer3.bes.dev2.aws.blockchaincloudpoc-develop.com:443
        - url: http://peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:443
      trust: "CA_OR_TOFU"
      
      
      servicetype: ClusterIP
      ports:
        tm: 443        
        db: 3306
        client: 8888
      mountPath: /etc/tessera/data
      ambassadorSecret: peer4-ambassador-certs
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/carrierkav-bes/crypto/peer4
      serviceaccountname: vault-auth
      keyname: credentials
      tm_keyname: tm
      tlsdir: tls
      role: vault-role
      authpath: besucarrierkav
 
    proxy:
      provider: "ambassador"
      external_url: peer4.bes.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443      
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
