apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturerkavm-peer1ibft
  namespace: manufacturerkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturerkavm-peer1ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: feature-1562
    path: platforms/hyperledger-besu/charts/node_besu
  values:
    metadata:
      namespace: manufacturerkav-bes
      labels:
    replicaCount: 1
    staticnodes:
      - "enode://109d81a916558aa6af525ea286d9eed397dfc764ebee60b4e33cff9e45ce8c2168d51991e31f6fe6be9552fc425ff4a0ca49462f3529a994d798d1a519c70841@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      - "enode://8971c44884268f23c0c5a057c5e8e97d70c1962bb14bd9717337c57592f4fca3c0b6bb80137e3bd7ff131dd51b7b7258bdb77e2cf0f2402bf7e621361f7fbbd6@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      - "enode://e128c96ed4f6a5f700ddb5c7cd4c20756314014bef80864fab342a28cc3a4a39eaa7fddb9101b32d7051d04556f8ac4b9ca651cb1888fcfcf16b211c3bf49a4d@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      - "enode://356655d133e08fece5eb9a8f0631d161a2f70b9a8541142639888c89e0e6e17ae25cbf02dfdeab756b1ce12b965552c63a239f5075964915aef9cb8a98e26293@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      - "enode://cb67af2c21bf94c614ca522bfe99814e9b62ad41cd019b7110451fff43ecdd7dab80221391c09a5c5e1348187b59b0026aa1896e1663740d926170b1aaa49289@c-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      - "enode://6ceadc6193ed858972a3e4e7e0ea8aae2824ca916ce045d8fb496146b6503a029b62e8b4bf75846348b8494fe7a29c87a3655103c8107926aef04bdfc0dc93bb@m-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15061"
   

    liveliness_check:
      enabled: false
    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5
 
    proxy:
      provider: ambassador
      external_url: manufacturerkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15061
      rpc: 15062

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0     

    node:
      name: m-peer1
      consensus: ibft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8590
        ws: 8546

    tm:
      type: tessera
      tls: True
      
      url: "https://m-peer1-tessera.manufacturerkav-bes:8888"
      
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/manufacturerkav-bes/crypto/m-peer1
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besumanufacturerkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGNkNjc5YzQ3MTE0NDM3MGU0OWY4YjU2NGJkYjJkNGM1ZDE4YjkxNjQ5NDQ4ZjMwNGQ3MjhiYmJkZmZiYTQxYmVkNDBlYmMxMWIzNWVhOTY0ZGQ5NGFkY2VmMzc0ZDgwYjliM2QzMDlhMjFmOTRhNDJiYTMzNGI4ZDA0ZGQ5NGQyZDQxMmZmMTY4NDg5Mzc5MDFkODgyYWFjMmNkNTFlYTU3Y2U0NmI4MDg0MDAwMDAwMDBjMCIKfQ==
