apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkavvalidator3ibft
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkavvalidator3ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: feature-1562
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://72f2f6430f771c98d5ec4b97163f1dd38389408f245e47be1bb4d847d5ff2ee2cc8a624ca782916a7abf6616f729b543078e98e1fc4dcfa7cca16f8fcb724b1d@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      
      - "enode://2bf94ce7d4bc67bfc6d0a5cde237e453b92d77a8bc21b6fd8d00c3c9c10e142040958f7f07e1c39530e0b3f597b96992f7d21af03644475bd7f10ec96709444b@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      
      - "enode://a51d3f81a59ebc8bdf2018be569e6a570921148371dd0fac4bf4b744863fc299aeac25451aaea5c395a4654f94fb3035f5cfade06cbcdfa834af01e433185e84@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      
      - "enode://0bfd1a87465f93d0118929b1d9ec6d9352efd6aaf49ba46da9269bea9c6ccff39695133462ab59877528d7bd7e22bc9d5211dfbfba69363967940e2f40365338@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      
      - "enode://be9fb25941246d46dda0fdd0fd59fb86fac88306846c4911b2ed0bc1799e8e794caf341df36f6b3793faeb3652763bb509fa3ee1b49c3d94b81d549256bd7167@c-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      
      - "enode://a076b89c56dbe6bcd58bec387bd53e5e5ba6a8b5c25508c00a8ba917889830d14118f0d19bcb7d2dcdce18c2f3cf1807c30601ec77c7ba5e00e6f5d0f9df3687@m-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15061"
      

    metadata:
      namespace: supplychainkav-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychainkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15045
      rpc: 15046

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator3
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/supplychainkav-bes/crypto/validator3
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGU3YTczZjBlOTIzNWYyYzllNWI0MWI1Yzc3MTM3NzEwNWU5OGNkNDE5NDBlOTk1MjM5MTUyZmQ3YzY5NDhmYmUwNzNmZDRiY2NhNzJkOTUzOWI5NGQ5Y2ZlNDE1ZjUwNDM3NmRkODk3YzgyMGMyMDkyZjU5ZDZjOGY4MmI5NGE3MTkwOGY3YzdmMzhiM2NhZjg1OWQ0NWUyNDI0ODZjMjM1ZjY1Nzk4MDg0MDAwMDAwMDBjMCIKfQ==
