apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkavvalidator4ibft
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkavvalidator4ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: feature-1562
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://b502e111b828f7b2daeedbb6c6528e6c47843f32ba50c6a7a5a79be723dac40995e79a30bb0fa1baa88a7a6868411d9ae713d2e6a19477a7694a3d827e78a154@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      
      - "enode://32d407a41a7387472fcc55ffb67665b43af67d2a8cbde1587cab570edf66cb139dbb734f743a1a9a31ea208088ec7d9e9719ae729ef26f7dd7e528069a0686ab@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      
      - "enode://407f075de777307f1a72586feaedebd4579134d10be2fe544e26daa5c839bb6df94054aade4370642a194a34f1bc2c8a923607585105fdf758b0241d2b173772@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      
      - "enode://2b08e56c0c11ad75be2953c5a1c7e009bd39bbf75f11837b47488a95bc059a6bfc94c79247ac49c38eef0d10be79fce8de8e07740da7b4fd51d5131f18a6f3df@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      
      - "enode://7b802b34599d75582bf5b9c0a0f0e9957f38876a6352783b1dabb9c35a0efc5224ab59fa05bcf2a8d4f6bd3db30941dd5bc08060fcfe621cc74fa10bb8744137@c-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      
      - "enode://d5da0afa7d037409ab7be42816521635e8229e98c505678a4bf37b0b51abb7dda558522421cfc1f71987387fbc89b792ce9a5beb35bcac721b641650beac1f72@m-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15061"
      

    metadata:
      namespace: supplychainkav-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychainkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15047
      rpc: 15048

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator4
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://adf3753447cd347f4a78818d36eab86e-351981302.eu-west-1.elb.amazonaws.com:20002
      secretprefix: secretsv2/data/supplychainkav-bes/crypto/validator4
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGE5ZjYyYTNkNzQ4ZTRhMDdiYTlmODUyMjkzZDVkMDgzOTAyN2ZmN2Y5NDQ0YTBmYTM4YTMwYjhjMWJmN2Q1OWM1NDBjNDQ1MDNmOTA1MzI5Y2U5NGMwNGQ0YTZmMDRlYWMxOWQwZjJjZmQzOWRlNDIxYWJlYzZlM2UwNWI5NGMwOWVkMWQ1MDExOTEzNjlhNGU0NGFlNTZlMzBkM2I5OTA3N2MxMGU4MDg0MDAwMDAwMDBjMCIKfQ==
