apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkavvalidator2ibft
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkavvalidator2ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: feature-1562
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://5a51114c036cf5d7933ddf2215ea43ab4bfc0fe5e4e6eb39330e04279c12f1198a941cb68713a1ec6b08ea4a72761df4bd1aa1fd1ce495205550d74bf600d8eb@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      
      - "enode://b09db89f23ccdde61115ad1e0a8a6ac89854eb7779274280933e7cf438e244cc9f992b4baad3857c9b8a84eb2404796b0c038f1ed8164138309cf3d9d011ce60@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      
      - "enode://06456bdbcbffa51e6e21aa1eb19f7bfde425c6722719ac82d8648cd4463238ec727c85db8a5dbaa246960383d551c0c472cb125d3ea8b75bbf9e4b878f4d55ca@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      
      - "enode://dbdd0041d1b1918c9b250ed32131bbe137f88f0b4a9fe79ee55671ba5fbf7674f34a988677b5410e4ac4417ce22b555214dcde04816cf2fdd9f809b73757888a@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      
      - "enode://95c462aa3fc853e7ef8bc040d41d872f0f410c4a22abac80b1b3b719d69ee7d6e0aae68ae8611ec91a09ff1e98d17987f4db9fdaa13828e0aaca2cb631081cab@c-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      
      - "enode://fe2163d6f530afe3bed475e7e47776aec879e52fb3b7c1a0d93be0f0595f14cc58b2d896dc1a2bcb1c789ac08618ef06274ac11807691acba559e49d7147c9a8@m-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15061"
      

    metadata:
      namespace: supplychainkav-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychainkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15043
      rpc: 15044

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://adf3753447cd347f4a78818d36eab86e-351981302.eu-west-1.elb.amazonaws.com:20002
      secretprefix: secretsv2/data/supplychainkav-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDVjMjlmOWU1NTNmMDZmMTM5ZDU0MjY5OWE4ZmIxODA2YzNhMTViZTM5NDVkNTQzODQyYTU1OTZkOTllYjBmMTE5NTI3NGYwNmQxNTJmYzcxNmI5NDY4N2Q0YTkzNGM4YTE3MWFmZjEzM2U5ODVmY2YyZGQ3ZDhhY2ZhZTk5NDYzYjZhYzc2MTE0MjJmOWUyM2UwOTFlZDBlNDM1OWNhYWEwZmMyMTQ4MDg0MDAwMDAwMDBjMCIKfQ==
