apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkavvalidator4ibft
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkavvalidator4ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: besu-privateTx
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://66ba3720f525762d6d3841563835cc0298c44bbdc66c212c2278f4ee45f2d66f29ede68c3089914afc8ce495b44e527be13d7eb064540d4f7f9f19548a61e66a@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      
      - "enode://71a9b6549fb503557e05d5d48186123514997f146cbf8b90f9e2e42cddea76d110143ca158b303e3004c1ca72d4ee84fb7d966879d68c1d561e1855ff8bec8b6@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      
      - "enode://b3ec4831b48fcd887957674ff93c8e2d9cee15e7da01f17189fd1126f5da77f71530be6975c6c5c7718bda6d456369bf3251d0939ff7de8f7ca6416f03eb5161@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      
      - "enode://39f7d55efac9ea7e60ff4d5e4c4b303166940a60b82405276f66fc74a23206e65eae61ce219834d7649bbf0c0e1828a0bdce4a036a5618237a383252a6202ec2@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      
      - "enode://aa92bb00b088641a18999b63e33cef90a18e7eede6725571696e5825ac0f82fc222896917cba1949d18af1f358b331fa2c1578def3543dc8eadae152c45c6099@peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      
      - "enode://eee6c19be04ddeb88d2d34e0d3df3475f615f90c7c48699da61f0792bc5d5e7a1d72f068ffbe8059a41de14eae176894f9b56279d8021b17dbf00d4ac3f5233b@peer2.bes.dev2.aws.blockchaincloudpoc-develop.com:15062"
      
      - "enode://e4395e50b6fb69adafbdd627e50024e80fc22db20c9f19854e3c6b495c7f73ee912bc85cfde576aa0990b65598062541276011af080274aabde3ba2fefda0428@peer3.bes.dev2.aws.blockchaincloudpoc-develop.com:15065"
      
      - "enode://f0c8fd7ba9e085f396cdded1143198f4f1d3421334fecdbfa59510272ea5ccf560430dbc16928790b1d4957b84ab810c34a57df09b554fe4ff3490d37563b990@peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:15068"
      

    metadata:
      namespace: supplychainkav-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychainkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15047
      rpc: 15048

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator4
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/supplychainkav-bes/crypto/validator4
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGE4MWJhY2EyOTg1MzljMTJjYmM3YmVkN2I4YWExZWM5NTljMzljYWE5NDY3ZGM2ZTRiZjQ2NGIyYzU2ODdmNTY5NzM1MDc2OWRhYjQ1NTMxMGM5NGMzNGNmNWNiMGE2NDAzMWNlNjNkNDZhNTcyZGQxZjBmNGFlNmRiOWY5NDBjZjBlMGVjZWU5ODE0NTdlNDc5MDFiOGExMDY4YjhhZmVjNDU0NmQ4MDg0MDAwMDAwMDBjMCIKfQ==
