apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkavvalidator4ibft
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkavvalidator4ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: besu-privateTx
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://7d7df027355ab937ed4d4d8e877e93f321fa1ba9b84788f45237b903f2953ee5b8758428075ebaed72f15ce39c9d724103cce66c2cae7bf4457e4fb71b3abc47@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      
      - "enode://83452bb4e046ed23665af49e8e4592ee383856106a635c41a3cddf26036a7a71b80b224d854948a1d75f84bf0258f7e26c04f3edb4c3337deea94ce91e6ae2cd@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      
      - "enode://c64c3045bcb41d15135c2b0d1d4b0c4b3b3228534c3eec69ba4b5dde19e8318ee72a60d1ed48b2227edc2b49c186976e2d94c8789f8212b9984e2bae8abd268d@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      
      - "enode://17472b37dfec0b7eb58ab91ebcc85e26d92017c580a0bf686b16c2fabc41f75211372fad611980928851fa75f1d29f88ab040b5b2092067831cb76d651e2cef5@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      
      - "enode://c91c0caddb8c945c2e85e3220d1aa7636498fc1730c8552f1225dcd83aeb4fd5d58f3d67a88066c7b247fe8bb1a4bf2250307e925fb2d065306ed31c017bbf0e@peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      
      - "enode://721a7935cf0557e9dfe2816a8ed68a52534309d460a074294bc4c552eeda130de311be42f63c5c56f8df922a1ba01388005670789f6afcb5ed34afaca2e44be3@peer2.bes.dev2.aws.blockchaincloudpoc-develop.com:15062"
      
      - "enode://5c75163de3a4fb542f2c0d9a6f96f09cb4d6715656a39e05e812bf36ec331d334d55a4725a28200bef595b681b688359ea89c2697385155a5777eef104c80b20@peer3.bes.dev2.aws.blockchaincloudpoc-develop.com:15065"
      
      - "enode://27ee984a01f0e1f307c4b0b171e4bfa687acdee6d557ef0004063a2dff274b90f2640c9f4ef1a03d413a70ecffdae2fe0df7e2c874a79d33cebc6f74b258ee9e@peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:15068"
      

    metadata:
      namespace: supplychainkav-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychainkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15047
      rpc: 15048

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator4
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/supplychainkav-bes/crypto/validator4
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGZhOGU3MTM3Y2RmMjVkY2E1Nzg2NWUxOTMxZmY5NjhkMWZmNzE0ZGE5NDkyMzBjNzQzZGIwZWI5MjliODVhNDRlMjMwMTRjZDc2OThlOGViNjA5NDcyMTI2NjhkYjVhNzI2OGNlMTFhNzA4ODAyN2E4YzNmZDZlYWU0OGM5NDc0NTFmY2ZjZmRkNjJmNTkyNWNhYjhlMjUzOTFhNDQ5NWU1ZmY1MWU4MDg0MDAwMDAwMDBjMCIKfQ==
