apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkavvalidator2ibft
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkavvalidator2ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: besu-Tx
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://5973d9b1862b5a930f6a433ba2ed51331454f2b9b968399e42ffbfcdaa1cca8e9ad661036ec31fff1805d1f41dcd95147b19448dd9e843be8486e46cacec0704@validator1.supplychainkav-bes:15041"
      
      - "enode://74d43efa00b0997c4eb6d42379542828a70584c9fe5da39f498ce4f14315fe8bf9495eca2d7b489db1858b3d4e0859eb54fd36877991a0610f395ae06f1a6722@validator2.supplychainkav-bes:15043"
      
      - "enode://60520dc4fc5e3918637211d42d5a22c1430e28b84e5fa89bf1ac2e81598e3fb0049c19967bf1a48edace7d7d65758067027c9570f00822e2a1708a13f52e4c32@validator3.supplychainkav-bes:15045"
      
      - "enode://4c0ba3b2622d120d1e09748e5049c553106850055c88c7c7f6910eee305e4b9ee9bef32f5d30b0376ff3bfac1acf4044ac5d50e86731f91641b2da800c2a2172@validator4.supplychainkav-bes:15047"
      
      - "enode://a7cb9834ab25f805f9c88ece30536eaf63433c5797c0bbddc81fde3467cbea3968a1093fb7acf8e111a8707b82120e573607b266e3bd3836893d6bd517a97037@c-peer1.carrierkav-bes:15049"
      
      - "enode://47a43e12a3b654fc967dd8febcf33bb33ea72c2132be880d95e39a0272d37d39b2dad0c1c4f4dee73bcc611206b099f686cee3aa4da110597b7bb2803a79e849@m-peer1.manufacturerkav-bes:15061"
      

    metadata:
      namespace: supplychainkav-bes
      labels:

    ambassador:
      external_url_suffix: supplychainkav-bes

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychainkav.supplychainkav-bes
      p2p: 15043
      rpc: 15044

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/supplychainkav-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGE3NmJhMGE0ZWNhZTQ4ZWQ1ZTJhMGYwOWFhYWQ5OTM3Yjk4N2JmOWQ5NDc4MTc3YjgxZmM1ZDMyNGI0MzU0ZjA5ZDliOWQyZTg2YmQ4NTYwNGQ5NGEzNTNhMTM1ODU3ZTIzZGM5NTg4ZTAyZGFjZTAyNzlkNzMwOTc1YTQ5NDY2ZjA2NTYxOTBjYjJiOTkzMjhiYzA4YTVmZDU2YjgyYzBlM2QxNzc4MDg0MDAwMDAwMDBjMCIKfQ==
