apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkavvalidator2ibft
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkavvalidator2ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: besu-privateTx
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://f7cf1942067d5cfba163f4b00112ae09b9537b2b0aaeadbaec3b1a484ca6698d87330f83914e634be4b50e0593ed167b3ca7e5f4003919b8e39aa3dc669362f2@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      
      - "enode://a442a22c778d89b960ffc2f42683fa7a896b33ce3157bb9799808d78045a580110fe4498db8332a9aee1e4e8ba2b1a696ea28ece7b1b0d9e133b5d590841c84e@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      
      - "enode://4f8f22134f18b91aac2804023b461801f4609b5b5631171899b17358571819b463d375cae5cea675b048f434cf497f0c61549f0cdce7746e07d29e8bc5df28df@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      
      - "enode://634ee3a61ffc3494b86da535475844ecc993b2c168b73546fee0c0acaa83a5b5eed9c8414e5546f00b3972747b99c0462ade18e3c02ce557f29a54e3e209224e@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      
      - "enode://8a4da6572ea50414d2b4e12f92006986e28795145e5fbc728c1fc3e5eb2732e192de5676993ff1ec6cd6f3459739099d54bd2f0d9380c87891b8d674420d2f2d@peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      
      - "enode://bfc6a08d79a0063743885bdc35bd5220b07f5f18aed4c50a5f587646c6ff4b72e77c7de5afe02976bdc8bd2dab3a6bdf74038058cf2687386bd6116f734774b9@peer2.bes.dev2.aws.blockchaincloudpoc-develop.com:15063"
      
      - "enode://758344df0d38f7be07707882d4a2d7620eb69221f79e23d05b8972baa3240d12d770debdc5e8cbf0dd90275f7bd3a1fad0694314a134714fce0e9fa9be894fc6@peer3.bes.dev2.aws.blockchaincloudpoc-develop.com:15067"
      
      - "enode://f0eae16c8f88dd01fa8c7e97cabd3a672177c5bb8ba5c3d274c1f81d57d4cfc01126fcf1586c884e652fd0f7753e79c8d4d7d51c6c33c99ca783b4f4a5f9b3f5@peer4.bes.dev2.aws.blockchaincloudpoc-develop.com:15001"
      

    metadata:
      namespace: supplychainkav-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychainkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15043
      rpc: 15044

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/supplychainkav-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NGVmOTI1YzJhOTE1ZmI3NTNiODQ2ZDA4YjQ3MGVkM2M2MjA4YzAwOGI5NDU3ZjZhNTdmY2I2ZDU2ZTA4NTc2NDgyNTU5YzMyZmE1OWRjOTcyYTc5NDg1YzlkMzUwNjIyYjg5ZjE0ZDI5ZmQ3N2FmYjI5NGQwZTM1MmNmNzY5NDE3MjM4MDM3ZTIwODM2OThhMzIwZWQ2YjVhODVhMWFjNGYxMmMwZGQ4MDg0MDAwMDAwMDBjMCIKfQ==
