apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkavvalidator2ibft
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkavvalidator2ibft
  chart:
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: private-tx-express-app
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://9fa8f6b6c4b5dc85ad0f73bdc9b2558c6ce08adc1ea9aba244c354fc9f88e4008ba4dc7d730b9bdc365597b6e28b8eee4ce291d8a1be948827b8b36dd25837a6@validator1.bes.dev2.aws.blockchaincloudpoc-develop.com:15041"
      
      - "enode://d82500a307cacfde7b222d1072362a6f94efd0d247f1b2f736ccde7a5673f872e83ed51d66272743ef58769f81c114292e3ec04bc385f2c3243a1b7b60a283c8@validator2.bes.dev2.aws.blockchaincloudpoc-develop.com:15043"
      
      - "enode://6190d8d7343e216a2fd2de44e024d91638b2edc832af104ee07d80bee2fcf0d23c5a480a9e650319a0c9af3b507270086fdd33d231977adb78043dda8c4b7fc2@validator3.bes.dev2.aws.blockchaincloudpoc-develop.com:15045"
      
      - "enode://a9f2f6885e4ef722437178c39dda3cab468056cfa6b78abb6fbecc579fcd98f32ea7a3ad15483f2d7e654bb2200c1127be625766e189760c4811f7bcfac30661@validator4.bes.dev2.aws.blockchaincloudpoc-develop.com:15047"
      
      - "enode://3c31d20d2801b1651711ae976d9b00a4e61994393e1dd7e73605571401ad30c271e9b54c4fcd26fb21e3477ab825777d6330e82225a32cfdef8e83f7d08d0c79@c-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15049"
      
      - "enode://f3ae852594a128305e3cf51c81f181a4f992e3d7890385e417c6ff9e321584cf72421ea3276398e261b5851bdc7ac54a1637154ae3ee2f7247b44096cb82d069@m-peer1.bes.dev2.aws.blockchaincloudpoc-develop.com:15061"
      

    metadata:
      namespace: supplychainkav-bes
      labels:

    ambassador:
      external_url_suffix: bes.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: supplychainkav.bes.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15043
      rpc: 15044

    images:
      node: hyperledger/besu:21.1.1
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator2
      tls: True
      consensus: ibft
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/supplychainkav-bes/crypto/validator2
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainkav

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDRmNDBhNzMxZWVmNzU4NGE5YjQ5YzgzOGQ4MjUzNGEwMGMwOTBkNzM5NDAwNWVmNmY1ZDE2ZDU2YzY0ZjE4NTNhMWI1NTNhMjdiMzc3OThlMzg5NDU5ODhkNGRlYWY5OWRhZWQ3NWRlYWZjMGY3NDdmZWZmZGEwMTUxZjI5NDk2NTM5OTUzMjU3MjliMWVkNzFmMWEzM2I4MmJmMTMzZmI4YmY4ZGY4MDg0MDAwMDAwMDBjMCIKfQ==
