---
apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-{{ $.Values.configMap.name }}
  namespace: {{ $.Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.name }}
    app.kubernetes.io/name: genesis-{{ $.Values.configMap.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}		
    app.kubernetes.io/managed-by: {{ .Release.Service }}			
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ibftConfigFile.json: |-
    {
      "genesis": {
        "config": {
          "chainId": 2018,
          "constantinoplefixblock": 0,
          "contractSizeLimit": 2147483647,
          "ibft2": {
            "blockperiodseconds": 2,
            "epochlength": 30000,
            "requesttimeoutseconds": 10
          }
        },
        "nonce": "0x0",
        "timestamp": "0x58ee40ba",
        "gasLimit": "0x1fffffffffffff",
        "difficulty": "0x1"
      },
      "blockchain": {
      "nodes": {
       "generate": true,
       "count": {{ $.Values.configMap.total_peer_count }}
       }
      }
    }
