apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainkav-ibft-job
  namespace: supplychainkav-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainkav-ibft-job
  helmVersion: v3
  chart:
    path: platforms/hyperledger-besu/charts/create_crypto_ibft
    git: https://github.com/kaverikhaneja/blockchain-automation-framework.git
    ref: feature-1628
  values:
    metadata:
      name: supplychainkav-ibft-job
      namespace: supplychainkav-bes   
      item:
        name: supplychainkav
    node:
      name:  validator1 validator2 validator3 validator4 peer1 peer2 peer3 peer4
      org:  supplychainkav supplychainkav supplychainkav supplychainkav carrierkav carrierkav carrierkav carrierkav
      type:  validator validator validator validator member member member member
    image: 
      repository: hyperledger/besu:1.5.5-SNAPSHOT-graalvm
      initContainerImage: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      pullPolicy: IfNotPresent
    configMap: 
      name: ibft-config
      total_peer_count: 8
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: besusupplychainkav				
      role: vault-role									
      serviceaccountname: vault-auth
      ibftprefix: secret/supplychainkav-bes/crypto/   
   